spring.application.name=backend
spring.profiles.active=local
spring.datasource.url=jdbc:mysql://localhost:3306/property_management_portal?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Security Configuration
propertymanagement.jwtSecret=propertyManagementSecretKeyForSigningJWTsMustBeAtLeast256BitsLong
propertymanagement.jwtExpirationMs=86400000
propertymanagement.googleClientId=217192771007-uldrjdjpoq9kll8b0cb28s8pcdhn0gm2.apps.googleusercontent.com

# AWS S3 Configuration
aws.s3.bucket-name=logiprime-documents
aws.s3.region=us-east-1
aws.s3.access-key-id=${AWS_ACCESS_KEY_ID:}
aws.s3.secret-access-key=${AWS_SECRET_ACCESS_KEY:}

# Multipart Upload Settings (Max 100MB)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
